name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install
      run: |
            npm install
    - name: Build icons lib
      run: |
            npm run icons:build
    - name: Run tests
      run: |
            npm run test
    - name: Build & Deploy application
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
            npm run deploy
