name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install
        npm install
    - name: Build application
        - npm run build
